-- drop
DROP TABLE IF EXISTS CHATLOG;

DROP TABLE IF EXISTS JOINROOM;

DROP TABLE IF EXISTS ROOMS;

DROP TABLE IF EXISTS USERS;

DROP SEQUENCE IF EXISTS CHATLOGID_SEQ;

DROP SEQUENCE IF EXISTS REACTIONID_SEQ;

-- create
CREATE TABLE IF NOT EXISTS
  USERS (
    USERID CHAR(5) PRIMARY KEY,
    USERNAME VARCHAR(40) NOT NULL,
    MAILADDRESS VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD VARCHAR(300) NOT NULL,
    USERIMGPATH VARCHAR(500) DEFAULT '',
    ROLE VARCHAR(20) DEFAULT 'USER',
    ENABLED CHAR(1) DEFAULT 'Y' NOT NULL
  );

CREATE TABLE IF NOT EXISTS
  ROOMS (
    ROOMID VARCHAR(5) PRIMARY KEY,
    ROOMNAME VARCHAR(50) UNIQUE NOT NULL,
    CREATEDUSERID CHAR(5) NOT NULL,
    DIRECTED BOOLEAN DEFAULT FALSE,
    PRIVATED BOOLEAN DEFAULT FALSE
  );

CREATE TABLE IF NOT EXISTS
  JOINROOM (
    ROOMID VARCHAR(5),
    USERID CHAR(5),
    PRIMARY KEY (ROOMID, USERID)
  );

CREATE TABLE IF NOT EXISTS
  CHATLOG (
    CHATLOGID INTEGER PRIMARY KEY,
    ROOMID VARCHAR(5) NOT NULL,
    USERID CHAR(5) NOT NULL,
    MESSAGE VARCHAR(500),
    CREATED_AT TIMESTAMP,
    FOREIGN KEY (ROOMID) REFERENCES ROOMS (ROOMID),
    FOREIGN KEY (USERID) REFERENCES USERS (USERID)
  );

CREATE SEQUENCE IF NOT EXISTS CHATLOGID_SEQ START
WITH
  1 INCREMENT BY 1;
